# Generated by Django 5.1.5 on 2026-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('seller', 'Adoption & Seller'), ('vet', 'Veterinarian'), ('caretaker', 'Pet Caretaker'), ('groomer', 'Pet Groomer')], max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('profile_image', models.ImageField(upload_to='user_profiles/')),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
