# Generated by Django 5.1.5 on 2026-01-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_image', models.ImageField(upload_to='pet_images/')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('certification', models.FileField(blank=True, null=True, upload_to='pet_certificates/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('dob', models.DateField()),
                ('about_me', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('google_map_link', models.URLField(blank=True, help_text='Paste Google Maps location link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcare.user')),
            ],
        ),
    ]
