# Generated by Django 5.1.5 on 2026-02-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='petcare.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcare.user')),
            ],
            options={
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
