# Generated by Django 5.1.5 on 2026-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0003_pet_views_count_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
