# Generated by Django 5.1.5 on 2026-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0004_pet_is_for_sale_pet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'role')},
        ),
    ]
