# Generated by Django 5.1.3 on 2026-02-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_appointment_payment_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_care_tasks', to='petcare.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_bookings', to='petcare.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_bookings', to='petcare.pet')),
            ],
        ),
    ]
