# Generated by Django 5.1.3 on 2026-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0008_carepayment_carereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carebooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
