# Generated by Django 5.1.3 on 2026-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0009_carebooking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('treated', 'Treated'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carepayment',
            name='payment_method',
            field=models.CharField(choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('card', 'Debit/Credit Card'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('card', 'Debit/Credit Card'), ('cash', 'Cash')], max_length=20),
        ),
    ]
