# Generated by Django 5.1.3 on 2026-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0010_appointment_amount_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
