# Generated by Django 5.1.3 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0011_appointment_doctor_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='carebooking',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
